name = "DogcraftApproved"
author = "William278"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e185c72a84abb14d6a6a9542a5f400986b9d8f99b821d99d7cee890a9e733526"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
