name = "DogcraftApproved"
author = "William278"
version = "7.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0ee063a02e75d8b49dbf86a7de01d0c0b614be9b09d4c030797119e5380d4f8"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
