name = "DogcraftApproved"
author = "William278"
version = "3.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d22163fb56e3bdc073403fdd93f8a1db589a8d964028634fa2692ddad7a0de30"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
