name = "DogcraftApproved"
author = "William278"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fc6ac249eabaefcdecf3c3ae5ae2acf34e32c2dada3b657c4cd3ce9fd96d303"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
