name = "DogcraftApproved"
author = "William278"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c56f6f354911e35c2b230cb09ba0e300667a82b8c8bd5179b357ee91ca9d2430"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
